<!-- application/views/scripts/API/index.phtml -->

<p><a href="<?php echo $this->url(
    array(
        'controller' => 'FriendDBController',
        'action'     => 'retrieve'
    ),
    'default',
    true) ?>">Retrieve All Users</a></p>

Users: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->id) ?></dt>
    <dd><?php echo $this->escape($entry->food) ?></dd>
    <?php endforeach ?>
</dl>
